#!/usr/bin/env bun
// Copyright (c) 2026 AwaCloud SAS
// Author: Matthieu Bouilloux
// SPDX-License-Identifier: Apache-2.0

// tools/fw-codegen/src/registry/index.js
/**
 * @fileoverview Generates `types/registry.generated.d.ts` — the
 * module-name → instance-type map that powers the optional **typed runtime**
 * facade (`@awacloud/fw/typed`).
 *
 * Ported logic-verbatim from `packages/front/fw/tools/types/codegen/index.js`
 * (fw-tools mutualization W1a). The only adaptation is the path-resolution
 * seam: `SRC_DIR` / `TYPES_DIR` / `OUT_FILE` / `DIST_TYPES_DIR` now derive from
 * `PKG_ROOT = --pkg ?? cwd` instead of the tool's own location, so any
 * fw-shaped package can point the generator at its own `src/`.
 *
 * Unlike the `deps` one-shot (which bakes `deps` into source once), this is a
 * PERMANENT build step: the registry is a generated artifact that must be
 * refreshed whenever a module is added, removed, or its factory return type
 * changes.
 *
 * Mechanism: for each module discovered by the shared scanner, emit one entry
 *
 *     'hex': ReturnType<typeof import('../dist/types/io/codec/hex')['hex']['factory']>;
 *
 * keyed by the framework module name, indexing the emitted declaration's
 * exported binding. No value imports, no `import type` bindings → zero risk of
 * name collisions, and the instance type flows straight from the JSDoc-derived
 * `.d.ts`.
 *
 * Usage:
 *     bun cli.ts fw-codegen registry                       # write the registry
 *     bun cli.ts fw-codegen registry --check               # exit 1 if out of date
 *     bun cli.ts fw-codegen registry --pkg <dir>           # target another package
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, relative } from 'node:path';

import { scanAll } from '@awacloud/tool-fw-bundler/modlib';
import { printHelp, wantsHelp, isMainModule } from '@awacloud/tool-fw-bundler/modlib';

// ─── Path-resolution seam ───
// The fw original derives these from its own file location (`tools/types/codegen`
// up to the fw package root). Here they derive from `PKG_ROOT = --pkg ?? cwd`,
// assigned by `resolvePkgPaths` before any scan/render. Declared as module-level
// bindings so `render` references them by the same names as the fw original.
let PKG_ROOT, SRC_DIR, TYPES_DIR, OUT_FILE, DIST_TYPES_DIR;

function resolvePkgPaths(pkgRoot) {
    PKG_ROOT = pkgRoot;
    SRC_DIR = resolve(PKG_ROOT, 'src');
    TYPES_DIR = resolve(PKG_ROOT, 'types');
    OUT_FILE = resolve(TYPES_DIR, 'registry.generated.d.ts');
    DIST_TYPES_DIR = resolve(PKG_ROOT, 'dist', 'types');
}

// ─── CLI help ───
const HELP_USAGE = 'bun cli.ts fw-codegen registry [--check] [--pkg <dir>]';
const HELP_FLAGS = [
    ['--check', 'Exit 1 (do not write) if types/registry.generated.d.ts is out of date.'],
    ['--pkg <dir>', 'Package root to read from (default: cwd). Resolves src/, types/, dist/types/ under it.'],
    ['--help, -h', 'Show this help.'],
];
const HELP_EXAMPLES = [
    'bun cli.ts fw-codegen registry',
    'bun cli.ts fw-codegen registry --check',
    'bun cli.ts fw-codegen registry --pkg packages/front/fw',
];

/**
 * Parse the `registry` subcommand argv.
 * @param {string[]} argv
 * @returns {{ check: boolean, pkg: string|null }}
 */
function parseArgs(argv) {
    const opts = { check: false, pkg: null };
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--check') opts.check = true;
        else if (a === '--pkg') opts.pkg = argv[++i];
        else if (a.startsWith('--')) throw new Error(`Unknown flag: ${a}. Run with --help.`);
        else throw new Error(`Unexpected positional argument: ${a}`);
    }
    return opts;
}

/**
 * Build the registry source text from the module catalog.
 *
 * @param {Map<string, import('@awacloud/tool-fw-bundler/modlib').ModuleInfo>} byName
 * @returns {string}
 */
function render(byName) {
    const entries = [...byName.values()].sort((a, b) =>
        a.moduleName < b.moduleName ? -1 : a.moduleName > b.moduleName ? 1 : 0
    );

    const lines = [];
    lines.push('// GENERATED by tools/types/codegen — do not edit.');
    lines.push('// Refresh with `bun run types:registry` after changing modules.');
    lines.push('//');
    lines.push('// Maps each framework module name to the instance type returned by its');
    lines.push('// factory. Consumed by `@awacloud/fw/typed` to give `resolve(name)` a precise');
    lines.push('// return type. Entries resolve against the emitted declarations in');
    lines.push('// `dist/types/` — run `bun run types` first.');
    lines.push('');
    lines.push('export interface ModuleInstanceMap {');

    for (const info of entries) {
        // Path from types/ to the emitted declaration (no extension).
        const relFromSrc = relative(SRC_DIR, info.file).replace(/\\/g, '/').replace(/\.js$/, '');
        const distDecl = relative(TYPES_DIR, resolve(DIST_TYPES_DIR, relFromSrc)).replace(/\\/g, '/');
        const spec = distDecl.startsWith('.') ? distDecl : './' + distDecl;
        const key = /^[A-Za-z_$][\w$]*$/.test(info.moduleName)
            ? info.moduleName
            : `'${info.moduleName}'`;
        lines.push(
            `    ${key}: ReturnType<typeof import('${spec}')['${info.bindingName}']['factory']>;`
        );
    }

    lines.push('}');
    lines.push('');
    return lines.join('\n');
}

/**
 * Pure programmatic API: scan `<pkg>/src` and return the registry source text.
 * Never writes. Throws if any module file is unparseable.
 *
 * @param {string} [pkg]  Package root (default: cwd).
 * @returns {{ text: string, moduleCount: number }}
 */
export function renderRegistry(pkg = process.cwd()) {
    resolvePkgPaths(resolve(pkg));
    const { byName, unparseable } = scanAll(SRC_DIR);
    if (unparseable.length) {
        throw new Error(
            `[codegen-types] ${unparseable.length} file(s) could not be parsed:\n  ` +
                unparseable.map((u) => u.file).join('\n  ')
        );
    }
    return { text: render(byName), moduleCount: byName.size };
}

/**
 * Run the `registry` subcommand CLI. Returns the process exit code.
 * @param {string[]} argv  Args after the `registry` token.
 * @returns {number}
 */
export function runCli(argv) {
    if (wantsHelp(argv)) { printHelp(HELP_USAGE, HELP_FLAGS, HELP_EXAMPLES); return 0; }

    let opts;
    try { opts = parseArgs(argv); }
    catch (err) { console.error('[codegen-types] ' + err.message); return 2; }

    resolvePkgPaths(resolve(opts.pkg ?? process.cwd()));

    const { byName, unparseable } = scanAll(SRC_DIR);
    if (unparseable.length) {
        console.error(
            `[codegen-types] ${unparseable.length} file(s) could not be parsed:\n  ` +
                unparseable.map((u) => u.file).join('\n  ')
        );
        return 1;
    }

    const next = render(byName);

    if (opts.check) {
        const current = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, 'utf8') : '';
        if (current.trim() !== next.trim()) {
            console.error(
                '[codegen-types] FAIL : types/registry.generated.d.ts is out of date. ' +
                    'Run `bun run types:registry`.'
            );
            return 1;
        }
        console.log(`[codegen-types] OK : registry up to date (${byName.size} modules).`);
        return 0;
    }

    if (!existsSync(TYPES_DIR)) mkdirSync(TYPES_DIR, { recursive: true });
    writeFileSync(OUT_FILE, next, 'utf8');
    console.log(
        `[codegen-types] wrote ${relative(PKG_ROOT, OUT_FILE)} (${byName.size} modules).`
    );
    return 0;
}

if (isMainModule(import.meta.url)) {
    process.exit(runCli(process.argv.slice(2)));
}
